name: CI

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - pnpm-lock.yaml
      - '**/*.js'
      - '**/*.ts'
  pull_request:
    paths:
      - package.json
      - pnpm-lock.yaml
      - '**/*.js'
      - '**/*.ts'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: ^9.15
    - run: pnpm install --frozen-lockfile
    - run: pnpm run typecheck
